### ISSUE TITLE
instana agent from Helm does not work

### ISSUE THREAD

**Issue by FleischKarussel** [instana/instana-helm-chart#4] opened 2018-07-19 08:54 UTC
Hello guys,

I've got following error message when initially starting up the instana-agent helm.
latest Rancher 2.0.6 with latest supported kubernetes 1.10.3, latest supported docker 17.3.2 is being used.

`Helm template --notes failed. Error: render error in "instana-agent/templates/secret.yaml": template: instana-agent/templates/secret.yaml:7:38: executing "instana-agent/templates/secret.yaml" at <b64enc>: wrong number of args for b64enc: want 1 got 0 : exit status 1`

answers used:
```
instana.agent.endpoint.host
instana.agent.endpoint.port
instana.agent.key
instana.zone
```

Has anybody else that same issue?

Best regards
Benjamin

**Comment by dusansusic** [comment] 2018-08-06 07:11
Hello, please provide full command you have used, just as it is so we can reproduce this issue.

**Comment by FleischKarussel** [comment] 2018-08-06 07:32
Hello @dusansusic,

I've imported the Helm Chart through Rancher 2.0(.6) GUI into a cluster.
Answered the variables with valid values.

Compared to that, I've tested the same answering values against the howto from https://docs.instana.io/quick_start/agent_setup/container/kubernetes/
and everything worked fine when manually importing the resulting yaml file.

Br
FleischKarussel

**Comment by dusansusic** [comment] 2018-10-15 12:51
@FleischKarussel from message you posted as issue description, i would say there was a problem with setting/passing key needed to run Instana-agent. Since you solved this issue with importing chart with GUI, I will close this issue. If your proplem reoccurs, please reopen this issue. Thanks

**Closed by dusansusic** 2018-10-15 12:51 UTC
